<#
.SYNOPSIS
    Build ONyX Client installer.
    Pipeline: PyInstaller → signtool (exe) → Inno Setup → signtool (installer)

.PARAMETER Version
    Version string embedded in the installer, e.g. "0.3.0"

.PARAMETER CertThumbprint
    SHA1 thumbprint of a certificate in Cert:\CurrentUser\My or Cert:\LocalMachine\My.
    Use generate-cert.ps1 to create a self-signed one.

.PARAMETER CertFile
    Path to a .pfx certificate file (alternative to CertThumbprint).

.PARAMETER CertPassword
    Password for the .pfx file.

.PARAMETER TimestampUrl
    RFC 3161 timestamp server URL.
    Default: http://timestamp.digicert.com

.PARAMETER SkipSigning
    Build without code signing (development/CI without a cert).

.EXAMPLE
    # Development build — no signing
    .\build.ps1 -Version "0.3.0" -SkipSigning

    # Self-signed cert generated by generate-cert.ps1
    .\build.ps1 -Version "0.3.0" -CertFile ".\onyx-codesign.pfx" -CertPassword "secret"

    # Certificate already in the Windows store
    .\build.ps1 -Version "0.3.0" -CertThumbprint "AABBCCDDEEFF..."
#>

param(
    [Parameter(Mandatory)]
    [string]$Version,

    [string]$CertThumbprint  = "",
    [string]$CertFile        = "",
    [string]$CertPassword    = "",
    [string]$TimestampUrl    = "http://timestamp.digicert.com",
    [switch]$SkipSigning
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$ClientDir    = $PSScriptRoot                              # apps/client-desktop/
$DistDir      = Join-Path $ClientDir "dist"
$InstallerDir = Join-Path $ClientDir "dist-installer"
$BundledBinDir = Join-Path $ClientDir "bin"

# ── Locate tools ─────────────────────────────────────────────────────────────

function Find-Signtool {
    $sdkBin = "${env:ProgramFiles(x86)}\Windows Kits\10\bin"
    if (Test-Path $sdkBin) {
        $found = Get-ChildItem "$sdkBin\*\x64\signtool.exe" -ErrorAction SilentlyContinue |
                 Sort-Object Name -Descending | Select-Object -First 1
        if ($found) { return $found.FullName }
    }
    $cmd = Get-Command signtool.exe -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return $null
}

function Find-Iscc {
    foreach ($base in @($env:ProgramFiles, "${env:ProgramFiles(x86)}")) {
        $p = Join-Path $base "Inno Setup 6\ISCC.exe"
        if (Test-Path $p) { return $p }
    }
    $cmd = Get-Command ISCC.exe -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return $null
}

$Signtool = Find-Signtool
$Iscc     = Find-Iscc

if (-not $Iscc) {
    Write-Error "Inno Setup 6 not found. Download: https://jrsoftware.org/isdl.php"
}

$DoSign = (-not $SkipSigning) -and ($CertThumbprint -ne "" -or $CertFile -ne "")

if ($DoSign -and -not $Signtool) {
    Write-Error "signtool.exe not found. Install Windows 10 SDK."
}

# ── Helper: sign file(s) ──────────────────────────────────────────────────────

function Sign-Files {
    param([string[]]$Files)

    if (-not $DoSign) {
        Write-Host "  [signing skipped]" -ForegroundColor DarkGray
        return
    }

    $args = @("sign", "/fd", "sha256", "/td", "sha256", "/tr", $TimestampUrl)

    if ($CertFile -ne "") {
        $args += "/f", (Resolve-Path $CertFile).Path
        if ($CertPassword -ne "") { $args += "/p", $CertPassword }
    } else {
        $args += "/sha1", $CertThumbprint
    }

    foreach ($f in $Files) {
        if (-not (Test-Path $f)) { Write-Warning "  not found, skipping: $f"; continue }
        Write-Host "  signing: $(Split-Path $f -Leaf)"
        & $Signtool @args $f
        if ($LASTEXITCODE -ne 0) { throw "signtool failed: $f" }
    }
}

function Write-BinaryIntegrityMetadata {
    param([string]$BinDir)

    $targets = @("lust-client.exe", "tun2socks.exe", "wintun.dll")
    $manifestLines = @(
        "# ONyX LuST runtime manifest",
        "# format: <filename> <sha256>"
    )

    foreach ($name in $targets) {
        $path = Join-Path $BinDir $name
        if (-not (Test-Path $path)) {
            Write-Warning "  runtime binary missing, skipping metadata: $name"
            continue
        }
        $hash = (Get-FileHash $path -Algorithm SHA256).Hash.ToLowerInvariant()
        Set-Content -Path ($path + ".sha256") -Value "$hash *$name" -Encoding ASCII
        $manifestLines += "$name $hash"
    }

    Set-Content -Path (Join-Path $BinDir "manifest.txt") -Value $manifestLines -Encoding ASCII
}

# ── Step 1: PyInstaller ───────────────────────────────────────────────────────

Write-Host ""
Write-Host "=== Step 1: PyInstaller ===" -ForegroundColor Cyan
Push-Location $ClientDir

Write-Host "  Building lust-client (onefile)..."
python -m PyInstaller --noconfirm LustClient.spec
if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed: LustClient.spec" }

$LustClientExe = Join-Path $DistDir "lust-client.exe"
if (-not (Test-Path $LustClientExe)) { throw "lust-client.exe not found after build" }
New-Item -ItemType Directory -Force -Path $BundledBinDir | Out-Null
Copy-Item $LustClientExe (Join-Path $BundledBinDir "lust-client.exe") -Force
Write-Host "  Writing runtime manifest + SHA256 sidecars..."
Write-BinaryIntegrityMetadata -BinDir $BundledBinDir

Write-Host "  Building ONyXClient (GUI, COLLECT mode)..."
python -m PyInstaller --noconfirm ONyXClient.spec
if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed: ONyXClient.spec" }

Write-Host "  Building ONyXClientDaemon (onefile)..."
python -m PyInstaller --noconfirm ONyXClientDaemon.spec
if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed: ONyXClientDaemon.spec" }

Pop-Location

# ── Step 2: Sign executables ──────────────────────────────────────────────────

Write-Host ""
Write-Host "=== Step 2: Sign executables ===" -ForegroundColor Cyan

$ClientExe  = Join-Path $DistDir "ONyXClient\ONyXClient.exe"
$DaemonExe  = Join-Path $DistDir "ONyXClientDaemon.exe"

# Sign the main executables
Sign-Files @($ClientExe, $DaemonExe)

# Optionally sign bundled VPN binaries in _internal\bin\
$BinExes = Get-ChildItem (Join-Path $DistDir "ONyXClient\_internal\bin\*.exe") `
               -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName
if ($BinExes) {
    Write-Host "  signing bundled LuST runtime binaries..."
    Sign-Files $BinExes
}

# ── Step 3: Inno Setup ────────────────────────────────────────────────────────

Write-Host ""
Write-Host "=== Step 3: Inno Setup ===" -ForegroundColor Cyan

# Write a temp .iss with the correct version patched in
$IssSrc = Join-Path $ClientDir "installer.iss"
$IssTmp = Join-Path $ClientDir "_installer_build.iss"

(Get-Content $IssSrc -Encoding UTF8) `
    -replace '#define AppVersion\s+"[^"]*"', "#define AppVersion `"$Version`"" |
    Set-Content $IssTmp -Encoding UTF8

New-Item -ItemType Directory -Force -Path $InstallerDir | Out-Null

Push-Location $ClientDir
& $Iscc $IssTmp
if ($LASTEXITCODE -ne 0) { throw "Inno Setup compilation failed" }
Pop-Location

Remove-Item $IssTmp -Force

# ── Step 4: Sign installer ────────────────────────────────────────────────────

Write-Host ""
Write-Host "=== Step 4: Sign installer ===" -ForegroundColor Cyan

$InstallerExe = Join-Path $InstallerDir "ONyXClientSetup-$Version.exe"
Sign-Files @($InstallerExe)

# ── Done ──────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "=== Build complete ===" -ForegroundColor Green
Write-Host "  Output : $InstallerExe"
if ($DoSign) {
    $certLabel = if ($CertFile -ne "") { (Split-Path $CertFile -Leaf) } else { "thumbprint $CertThumbprint" }
    Write-Host "  Signed : $certLabel"
} else {
    Write-Host "  Signed : NO  (pass -CertFile / -CertThumbprint to enable)" -ForegroundColor Yellow
}
